---
- name: Install RabbitMQ
  yum:
    name: '{{ item }}'
    state: installed
  with_items: rabbitmq_packages

- name: Start RabbitMQ service and configure on boot startup
  service:
    name: '{{ rabbitmq_service_name }}'
    enabled: '{{ rabbitmq_service_enabled }}'
    state: started