---
- name: Ensure user
  rabbitmq_user:
    user: '{{ item.name }}'
    password: '{{ item.password | default(omit) }}'
#    force: true
    state: '{{ item.state | default(omit) }}'
    vhost: '{{ item.vhost | default(omit) }}'
    configure_priv: '{{ item.configure_priv | default(omit) }}'
    read_priv: '{{ item.read_priv | default(omit) }}'
    write_priv: '{{ item.write_priv | default(omit) }}'
  with_items: '{{ rabbitmq_users }}'
